import React from 'react';

const ComoJogarPage: React.FC = () => {
  return (
    <>
      <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-800 text-slate-100 py-12">
        <div className="container mx-auto px-4">
          <header className="text-center mb-12">
            <a className="inline-block mb-6" href="/">
              <button className="bg-emerald-500 hover:bg-emerald-400 text-white px-6 py-2 rounded-lg transition-colors">
                ← Voltar para a Home
              </button>
            </a>
            <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Como Investir no Blockchain Bet Brasil
            </h1>
            <p className="text-xl text-slate-300 max-w-3xl mx-auto">
              Aprenda as regras, entenda como funciona o sistema de aplicações e descubra como maximizar suas chances de ser contemplado!
            </p>
          </header>

          <section className="bg-slate-800/50 rounded-2xl p-8 mb-12 border border-emerald-500/30">
            <h2 className="text-3xl font-bold text-emerald-400 mb-6">📋 Regras Básicas</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <div className="bg-slate-700/50 p-4 rounded-lg">
                  <h3 className="text-xl font-bold text-white mb-2">🎯 Formato das Aplicações</h3>
                  <p className="text-slate-300">
                    Cada aplicação consiste em <strong>5 prognósticos</strong> no formato <strong>X/Y</strong>, onde X e Y são números de 1 a 25; pode repetir e/ou inverter prognósticos livremente.
                  </p>
                  <p className="text-slate-400 text-sm mt-2">
                    Exemplo: <code className="bg-slate-600 px-2 py-1 rounded">15/20</code>, <code className="bg-slate-600 px-2 py-1 rounded">1/25</code>, <code className="bg-slate-600 px-2 py-1 rounded">10/5</code>, <code className="bg-slate-600 px-2 py-1 rounded">13/25</code>, <code className="bg-slate-600 px-2 py-1 rounded">17/5</code>
                  </p>
                </div>
                <div className="bg-slate-700/50 p-4 rounded-lg">
                  <h3 className="text-xl font-bold text-white mb-2">💰 Valor das Aplicações</h3>
                  <ul className="text-slate-300 space-y-2">
                    <li>• <strong>Blockchain Bet Brasil:</strong> R$ 5,00 por aplicação</li>
                    <li>• <strong>Invest Bet:</strong> R$ 1.000,00 por aplicação</li>
                  </ul>
                </div>
              </div>
              <div className="space-y-4">
                <div className="bg-slate-700/50 p-4 rounded-lg">
                  <h3 className="text-xl font-bold text-white mb-2">🏆 Sistema de Premiação</h3>
                  <p className="text-slate-300">
                    Ganhe acertando <strong>5, 4, 3, 2 ou até 1 ponto</strong>! Quanto mais pontos, maior o retorno.
                  </p>
                  <p className="text-slate-400 text-sm mt-2">
                    Distribuição: 50% (5pts), 20% (4pts), 15% (3pts), 10% (2pts), 5% (1pt), rateado entre os acertadores em cada etapa de pontuação.
                  </p>
                </div>
                <div className="bg-slate-700/50 p-4 rounded-lg">
                  <h3 className="text-xl font-bold text-white mb-2">🎁 Sistema de Bônus</h3>
                  <p className="text-slate-300">
                    <strong>Zero pontos não é derrota!</strong> Receba bônus e acumule aplicações grátis.
                  </p>
                  <ul className="text-slate-400 text-sm mt-2 space-y-1">
                    <li>• Aplicação Regular / Invest-Bet: R$ 0,625 / R$125,00 de bônus por aplicação com zero pontos</li>
                    <li>• A cada 8 aplicações com zero pontos: 1 aplicação grátis!</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>

          <section id="prognosticos-validos">
            <div className="w-full max-w-6xl mx-auto p-8 mt-12">
              <h2 className="text-2xl font-bold text-white mb-2 text-center">
                Tabela de Referência de Prognósticos
              </h2>
              <p className="text-gray-400 mb-6 text-center">
                Esta tabela serve como uma referência completa de todos os 625 prognósticos possíveis em nosso sistema, no formato &quot;x/y&quot;. Use-a para consultar e planejar suas aplicações.
              </p>
              <div className="overflow-x-auto rounded-lg border border-gray-700">
                <table className="min-w-full bg-gray-800 text-white">
                  <tbody>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">1/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">2/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">3/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">4/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">5/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">6/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">7/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">8/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">9/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">10/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">11/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">12/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">13/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">14/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">15/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">16/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">17/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">18/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">19/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">20/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">21/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">22/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">23/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">24/25</td>
                    </tr>
                    <tr className="even:bg-gray-800 odd:bg-gray-900/50">
                      <td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/1</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/2</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/3</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/4</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/5</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/6</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/7</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/8</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/9</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/10</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/11</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/12</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/13</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/14</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/15</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/16</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/17</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/18</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/19</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/20</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/21</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/22</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/23</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/24</td><td className="border-t border-gray-700 px-2 py-1 text-center text-xs md:text-sm whitespace-nowrap">25/25</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </section>

          <section className="bg-slate-800/50 rounded-2xl p-8 mt-12 border border-amber-500/30">
            <h2 className="text-3xl font-bold text-amber-400 mb-6">💡 Dicas Estratégicas</h2>
            <div className="grid md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <div className="bg-amber-500/10 p-4 rounded-lg border border-amber-500/30">
                  <h4 className="text-lg font-bold text-amber-300 mb-2">🎲 Diversifique Seus Prognósticos</h4>
                  <p className="text-slate-300">
                    Use prognósticos altos e baixos, pares e ímpares. A diversificação aumenta suas chances!
                  </p>
                </div>
                <div className="bg-amber-500/10 p-4 rounded-lg border border-amber-500/30">
                  <h4 className="text-lg font-bold text-amber-300 mb-2">📊 Consulte a Tabela</h4>
                  <p className="text-slate-300">
                    Use a tabela de referência para planejar combinações estratégicas.
                  </p>
                </div>
              </div>
              <div className="space-y-4">
                <div className="bg-amber-500/10 p-4 rounded-lg border border-amber-500/30">
                  <h4 className="text-lg font-bold text-amber-300 mb-2">🔄 Invista Regularmente</h4>
                  <p className="text-slate-300">
                    Com o sistema de bônus, cada aplicação com zero ponto (8x)= 1 aplicação grátis!
                  </p>
                </div>
                <div className="bg-amber-500/10 p-4 rounded-lg border border-amber-500/30">
                  <h4 className="text-lg font-bold text-amber-300 mb-2">🔍 Acompanhe os Resultados</h4>
                  <p className="text-slate-300">
                    Fique de olho nos resultados anteriores para identificar padrões.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section className="text-center mt-12">
            <a href="apostas">
              <button className="bg-emerald-500 hover:bg-emerald-400 text-white font-bold py-4 px-8 rounded-lg text-lg transition-all duration-300 transform hover:scale-105">
                🎯 Fazer Minha Primeira Aplicação!
              </button>
            </a>
          </section>
        </div>
      </div>
    </>
  );
};

export default ComoJogarPage;